Description: >
    Datadog server/APM agent

Parameters:

    Cluster:
        Description: ECS Cluster name that should run this service
        Type: String

    DesiredCount: 
        Description: How many instances of this task should we run across our cluster?
        Type: Number
        Default: 1

    ApiKey:
        Description: Install Datadog dd-agent using this API Key 
        Type: String            
        AllowedPattern: ^[a-f0-9]{32}$

    EnableAPM:
        Description: Enable Application Performance Monitoring (trace)
        Type: String
        Default: false
        AllowedValues: [false, true]


Metadata:
    AWS::CloudFormation::Interface:
        ParameterGroups:
            - Label: 
                default: Cluster Attributes
              Parameters:
                - Cluster
                - DesiredCount
            - Label: 
                default: Datadog Monitoring
              Parameters:
                - ApiKey
                - EnableAPM
        ParameterLabels:
            Cluster:
                default: ECS Cluster
            DesiredCount:
                default: Desired Count
            ApiKey: 
                default: Datadog API Key
            EnableAPM: 
                default: 'Datadog: Enable APM?'


Resources:

    CloudWatchLogsGroup:
        Type: AWS::Logs::LogGroup
        Properties: 
            LogGroupName: !Ref AWS::StackName
            RetentionInDays: 7

    TaskDefinition:
        Type: AWS::ECS::TaskDefinition
        Properties:
            Family: !Sub ${Cluster}-dd-agent
            ContainerDefinitions:
                - Name: dd-agent
                  Cpu: 10
                  Essential: true
                  Image: datadog/docker-dd-agent:latest
                  Memory: 128
                  Environment:
                    - Name: API_KEY
                      Value: !Ref ApiKey
                    - Name: DD_APM_ENABLED
                      Value: !Ref EnableAPM
                  PortMappings:
                    - HostPort: 8125
                      ContainerPort: 8125
                      Protocol: udp
                    - HostPort: 8126
                      ContainerPort: 8126
                      Protocol: tcp
                    - HostPort: 9001
                      ContainerPort: 9001
                      Protocol: tcp
                  MountPoints:  
                    - ContainerPath: /var/run/docker.sock
                      SourceVolume: docker_sock
                    - ContainerPath: /host/sys/fs/cgroup
                      SourceVolume: cgroup
                      ReadOnly: true
                    - ContainerPath: /host/proc
                      SourceVolume: proc
                      ReadOnly: true
                  LogConfiguration:
                    LogDriver: awslogs
                    Options:
                        awslogs-group: !Ref AWS::StackName
                        awslogs-region: !Ref AWS::Region
            Volumes:
              - Host:
                  SourcePath: /cgroup/
                Name: cgroup
              - Host:
                  SourcePath: /var/run/docker.sock
                Name: docker_sock
              - Host:
                  SourcePath: /proc/
                Name: proc

    Service: 
        Type: AWS::ECS::Service
        DependsOn: CloudWatchLogsGroup
        Properties: 
            Cluster: !Ref Cluster
            DesiredCount: !Ref DesiredCount
            TaskDefinition: !Ref TaskDefinition
            PlacementConstraints:
                - Type: distinctInstance
